blank_issues_enabled: true

contact_links:
  - name: Discord Python Polska
    url: https://discord.com/invite/VCyBDGH38e
    about: Dyskusje o tłumaczeniach.
  - name: Transifex
    url: https://explore.transifex.com/python-doc/python-newest/
    about: Strona do tłumaczenia.
