name: Błąd w tłumaczeniu
description: Zgłoś błąd w tłumaczeniu
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        **Chcesz to naprawić samemu??**

          - Wejdź na stronę projektu [dokumentacji Pythona](https://explore.transifex.com/python-doc/python-newest/).
          - Naciśnij przycisk „Join this project”, aby dołączyć do projektu.
          - Utwórz konto Transifex.
          - Na stronie projektu wybierz język polski.
          - Po dołączeniu do zespołu wybierz zasób, który chcesz poprawić/zaktualizować.

        Więcej informacji znajdziesz w naszym (README)[https://github.com/python/python-docs-pl/blob/3.14/README.md].
  - type: textarea
    attributes:
      label: "Opis błędu:"
      description: >
        Opisz szczegółowo lokalizację błędu.
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Wersja dokumentacji:"
      multiple: true
      options:
        - "3.9"
        - "3.10"
        - "3.11"
        - "3.12"
        - "3.13"
        - "3.14"
    validations:
      required: false
