on:
  push:
    branches:
    - '3.11'
  workflow_dispatch:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@master
        with:
          python-version: 3
      - run: pip install sphinx-lint
      - uses: actions/checkout@master
      - run: sphinx-lint